let suggestions = [
    "Rice",
    "Garlic Naan",
    "Butter Roti",
    "Roti",
    "Chapati",
    "Limca Lime n Lemoni PET Bottle",
    "sprite Can",
    "Pepsi Can",
    "7UP Can",
    "Thums Up Can",
    "Vanilla cupcakes",
    "Chocolate mud cupcakes",
    "Blueberry Cake",
    "Banana Cake",
    "Chocolate Cake",
    "Idli",
    "bread omelette",
    "Uttapam",
    "Upma",
    "Poha",
    "Basundi",
    "Gulabjam",
    "Ice-Cream",
    "Chocolate Ice-Cream",
    "Vanilla Ice-Cream",
    "Strawberry Ice-Cream",
    "Veg Roll",
    "Chicken Pizza",
    "Paneer Tikka",
    "Palak Paneer",
    "Mix Veg",
    "Butter Paneer",
    "Veg Maratha",
    "Amritsari Chicken Masala",
    "Butter Chicken",
    "Kadai Chicken",
    "Mutton Masala",
    "Mutton Kofte",
    "Dhokla",
];